- name: Create service account for Hadoop
  user:
    name: "hadoop"
    system: true
    state: present

- name: Create .ssh directory
  file:
    path: "/home/hadoop/.ssh"
    state: directory
    mode: 0755
    owner: "hadoop"
    group: "hadoop"

- name: Put public key onto all nodes
  template:
    src: "hp-hadoop.ssh.public"
    dest: "/home/hadoop/.ssh/authorized_keys"
    owner: "hadoop"
    group: "hadoop"
    mode: 0644

- name: Put private key onto master node
  template:
    src: "hp-hadoop.ssh.private"
    dest: "/home/hadoop/.ssh/id_ed25519"
    owner: "hadoop"
    group: "hadoop"
    mode: 0600
  when: inventory_hostname in groups['master']

- name: Create downloads directory for Hadoop
  file:
    path: "/home/hadoop/downloads"
    state: directory
    owner: "hadoop"
    group: "hadoop"

- name: Download Hadoop package
  get_url:
    url: "https://archive.apache.org/dist/hadoop/common/hadoop-3.4.1/hadoop-3.4.1-lean.tar.gz"
    dest: "/home/hadoop/downloads/hadoop-3.4.1-lean.tar.gz"
    checksum: sha512:822cb1531333847e740d942cacf24295a588255786afe11f11c8ff9695be1caae425ddbafd4fda8b0f1fce88336efa05f16d5425659ab225075864ab6b8702bf
    owner: "hadoop"
    group: "hadoop"

- name: Create bundle directory for Hadoop
  file:
    path: "/home/hadoop/bundle"
    state: directory
    owner: "hadoop"
    group: "hadoop"

- name: Extract Hadoop package
  unarchive:
    src: "/home/hadoop/downloads/hadoop-3.4.1-lean.tar.gz"
    dest: "/home/hadoop/bundle"
    remote_src: true
    owner: "hadoop"
    group: "hadoop"
    extra_opts:
      - --strip-components=1

- name: Create work directory for Spark
  file:
    path: "/home/hadoop/workdir"
    state: directory
    owner: "hadoop"
    group: "hadoop"

- name: Upload Hadoop environment configuration file (hadoop-env.sh)
  template:
    src: "hadoop-env.sh.j2"
    dest: "/home/hadoop/bundle/etc/hadoop/hadoop-env.sh"
    owner: "hadoop"
    group: "hadoop"
    mode: 0755

- name: Upload Hadoop core configuration (core-site.xml)
  template:
    src: "core-site.xml.j2"
    dest: "/home/hadoop/bundle/etc/hadoop/core-site.xml"
    owner: "hadoop"
    group: "hadoop"

- name: Upload Hadoop HDFS configuration (hdfs-site.xml)
  template:
    src: "hdfs-site.xml.j2"
    dest: "/home/hadoop/bundle/etc/hadoop/hdfs-site.xml"
    owner: "hadoop"
    group: "hadoop"

- name: Upload Hadoop cluster workers list (workers)
  template:
    src: "workers.j2"
    dest: "/home/hadoop/bundle/etc/hadoop/workers"
    owner: "hadoop"
    group: "hadoop"

- name: Upload Spark Hadoop configuration (sets HADOOP)
  template:
    src: "hadoop-profile.sh.j2"
    dest: "/etc/profile.d/hadoop-env.sh"
    mode: 0755

- name: Upload Java activation library
  get_url:
    url: "https://jcenter.bintray.com/javax/activation/javax.activation-api/1.2.0/javax.activation-api-1.2.0.jar"
    dest: "/home/hadoop/bundle/share/hadoop/common/lib/javax.activation-api-1.2.0.jar"
    owner: "hadoop"
    group: "hadoop"