services:
  spark-master:
    image: spark:3.4.3-scala2.12-java11-r-ubuntu
    entrypoint: ['/opt/spark/sbin/start-master.sh']
    environment:
      - SPARK_NO_DAEMONIZE=true
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
      - SPARK_EVENTLOG_ENABLED=true
      - SPARK_EVENTLOG_DIR=file:/mnt/spark-events
    hostname: spark-master
    ports:
      - '8080:8080'
      - '7077:7077'
    volumes:
      - ../data/:/mnt/data/
      - ../results/:/mnt/results/
      - ../docker/scripts/:/mnt/scripts/
      - ../benchmark/target/scala-2.12/:/mnt/jar/
      - ../temporary:/mnt/temporary/
      - spark-events:/mnt/spark-events/

  spark-history-server:
    image: spark:3.4.3-scala2.12-java11-r-ubuntu
    entrypoint: ['/opt/spark/sbin/start-history-server.sh']
    environment:
      - SPARK_NO_DAEMONIZE=true
      - SPARK_HISTORY_OPTS=-Dspark.history.fs.logDirectory=file:/mnt/spark-events -Dspark.history.ui.port=18080
      - SPARK_USER=spark
    hostname: spark-history-server
    ports:
      - '18080:18080'
    volumes:
      - spark-events:/mnt/spark-events/

  spark-driver:
    image: spark:3.4.3-scala2.12-java11-r-ubuntu
    environment:
      - SPARK_NO_DAEMONIZE=true
      - IW_CSV_DIRECTORY=$IW_CSV_DIRECTORY
      - IW_DATA_DIRECTORY=/mnt/data
      - SPARK_MODE=driver
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
      - SPARK_EVENTLOG_ENABLED=true
      - SPARK_EVENTLOG_DIR=file:/mnt/spark-events
      - IW_DRIVER_MEMORY=10g
      - IW_EXECUTOR_MEMORY=$IW_EXECUTOR_MEMORY
      - IW_EXECUTOR_CORES=$IW_EXECUTOR_CORES
      - IW_TOTAL_EXECUTOR_CORES=$IW_TOTAL_EXECUTOR_CORES
    hostname: spark-driver
    ports:
      - '4040:4040'
    command:
      - "/mnt/scripts/iw-submit.sh"
      - "${JAR_FILE_PATH}"
      - "${CLASS_NAME}"
    user: "185:185"
    volumes:
      - ../data/:/mnt/data/
      - ../results/:/mnt/results/
      - ../docker/scripts/:/mnt/scripts/
      - ../benchmarks/interwalled/target/scala-2.12/:/mnt/jar/benchmark-interwalled/
      - ../benchmarks/sequila/target/scala-2.12/:/mnt/jar/benchmark-sequila/
      - ../temporary:/mnt/temporary/
      - spark-events:/mnt/spark-events/

    deploy:
      resources:
        limits:
          memory: 10g

  spark-worker:
    image: spark:3.4.3-scala2.12-java11-r-ubuntu
    deploy:
      replicas: 4
    entrypoint: ['/opt/spark/sbin/start-worker.sh', 'spark://spark-master:7077']
    environment:
      - SPARK_NO_DAEMONIZE=true
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=10G
      - SPARK_WORKER_CORES=10
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
      - SPARK_EVENTLOG_ENABLED=true
      - SPARK_EVENTLOG_DIR=file:/mnt/spark-events
    ports:
      - '8081'
    volumes:
      - ../data/:/mnt/data/
      - ../results/:/mnt/results/
      - ../docker/scripts/:/mnt/scripts/
      - ../benchmark/target/scala-2.12/:/mnt/jar/
      - ../temporary:/mnt/temporary/
      - spark-events:/mnt/spark-events/

volumes:
  spark-events:
