services:
  spark-master:
    image: spark:3.5.7-scala
    entrypoint: ['/opt/spark/sbin/start-master.sh']
    environment:
      - SPARK_NO_DAEMONIZE=true
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    hostname: spark-master
    ports:
      - '8080:8080'
      - '7077:7077'
    volumes:
      - ../data/:/mnt/data/
      - ../results/:/mnt/results/
      - ../docker/scripts/:/mnt/scripts/
      - ../benchmark/target/scala-2.12/:/mnt/jar/
      - ../temporary:/mnt/temporary/

  spark-driver:
    image: spark:3.5.7-scala
    environment:
      - SPARK_NO_DAEMONIZE=true
      - INTERWALLED_CSV_DIRECTORY=/mnt/results/default.csv
      - INTERWALLED_DATA_DIRECTORY=/mnt/data
      - SPARK_MODE=driver
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    hostname: spark-driver
    ports:
      - '4040:4040'
    command:
      - "/mnt/scripts/iw-submit.sh"
      - "4G"
      - "10G"
      - "10"
      - "$IW_APP_COMMAND"
      - "$IW_DATA"
      - "$IW_BENCHMARK"

    volumes:
      - ../data/:/mnt/data/
      - ../results/:/mnt/results/
      - ../docker/scripts/:/mnt/scripts/
      - ../benchmark/target/scala-2.12/:/mnt/jar/
      - ../temporary:/mnt/temporary/

    deploy:
      resources:
        limits:
          memory: 4G

  spark-worker:
    image: spark:3.5.7-scala
    deploy:
      replicas: 4
    entrypoint: ['/opt/spark/sbin/start-worker.sh', 'spark://spark-master:7077']
    environment:
      - SPARK_NO_DAEMONIZE=true
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=10G
      - SPARK_WORKER_CORES=10
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - '8081'
    volumes:
      - ../data/:/mnt/data/
      - ../results/:/mnt/results/
      - ../docker/scripts/:/mnt/scripts/
      - ../benchmark/target/scala-2.12/:/mnt/jar/
      - ../temporary:/mnt/temporary/