---

x-spark-common:
  &spark-common
  image: ${SPARK_IMAGE_NAME:-apache/spark:3.4.4-scala2.12-java11-ubuntu}
  environment:
    SPARK_NO_DAEMONIZE: True
    SPARK_MASTER_HOST: spark-master
    SPARK_MASTER_PORT: 7077
    SPARK_MASTER_WEBUI_PORT: 8080

services:
  spark-master:
    <<: *spark-common
    command:
      - /opt/spark/sbin/start-master.sh
    container_name: spark-master
    hostname: spark-master
    ports:
      - "7077:7077"
      - "8080:8080"

  spark-worker-1:
    <<: *spark-common
    command:
      - /opt/spark/sbin/start-worker.sh
      - "spark://spark-master:7077"
      - "--cores"
      - "2"
      - "--memory"
      - "4G"
      - "--host"
      - "spark-worker-1"
      - "--webui-port"
      - "8201"
    container_name: spark-worker-1
    hostname: spark-worker-1
    ports:
      - "8201:8201"

  spark-worker-2:
    <<: *spark-common
    command:
      - /opt/spark/sbin/start-worker.sh
      - "spark://spark-master:7077"
      - "--cores"
      - "2"
      - "--memory"
      - "4G"
      - "--host"
      - "spark-worker-2"
      - "--webui-port"
      - "8202"
    container_name: spark-worker-2
    hostname: spark-worker-2
    ports:
      - "8202:8202"
